baseURL: http://example.org/
languageCode: en-us
title: Portfolio website for Linli Ding
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      HERE ARE THE DATA ANALYTICS PROJECTS THAT 
      I HAVE BEEN WORKING SO FAR.
    title: Hey, welcome to my portfolio website!
  blog: {}
  contact:
    address:
      - city: London, NW6 1RZ
        country: the United Kingdom
        street: 14 Blackburn Rd
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ellen.ding01@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (UK) +44 7732 765143
        #how to? China: (China) +86 13094830823
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Linli DING
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
        #label: Twitter
        #url: https://www.twitter.com
      #- icon: fa-facebook
        #label: Facebook
        #url: https://www.facebook.com
      #- icon: fa-instagram
        #label: Instagram
        #url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/lld2-c
      - icon: fa-linkedin
        label: LinkedIn
        url: www.linkedin.com/in/linli-ding
      - icon: fa-wechat
        label: Wechat
        url: https://msng.link/o/?https%3A%2F%2Fu.wechat.com%2FMEKzB2DM8gvT-KA6oYu3ljc=wc
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    #button2:
      #- name: Log In
        #url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      #- name: Generic Blog
        #url: blogs/ipsum
      #- name: Elements
        #url: elements.html
    menu: Menu
    subtitle: by Linli DING
    title: CREATED
  tiles:
    enable: yes
    showcase:
      - image: stock_news.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Aliquam
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
